export enum ApiEndPoint {
  WEAPONS = 'Weapons',
  WEAPONS_COMPLETE = 'CompletedWeapons',
  ARMORS = 'Armors',
  GENERAL_GEAR = 'GeneralGears',
  BOMBS = 'Bombs',
  BOMBS_COMPLETE = 'CompletedBombs',
  TRAPS = 'Traps',
  TRAPS_COMPLETE = 'CompletedTraps',
  AMMO = 'Ammunitions',
  AMMO_COMPLETE = 'CompletedAmmunitions',
  RUNES = 'Runes',
  MONSTERS = 'Monsters',
  MONSTERS_COMPLETE = 'CompletedMonsters',
}
