/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Availability } from './availability';
import { Source } from './source';


export interface AlchemicalItem { 
    id?: number;
    name?: string | null;
    weight?: number;
    cost?: number;
    description?: string | null;
    effect?: string | null;
    availability?: Availability;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

