/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AlchemySkillLevel = 1 | 2 | 3 | 4 | 5 | 6;

export const AlchemySkillLevel = {
    NUMBER_1: 1 as AlchemySkillLevel,
    NUMBER_2: 2 as AlchemySkillLevel,
    NUMBER_3: 3 as AlchemySkillLevel,
    NUMBER_4: 4 as AlchemySkillLevel,
    NUMBER_5: 5 as AlchemySkillLevel,
    NUMBER_6: 6 as AlchemySkillLevel
};

