/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Availability } from './availability';
import { WeightClassification } from './weightClassification';
import { Source } from './source';


export interface Armor { 
    id?: number;
    name?: string | null;
    stoppingPower?: number;
    defaultReliability?: number;
    availability?: Availability;
    enhancementSlots?: number;
    encumberanceValue?: number;
    weight?: number;
    cost?: number;
    description?: string | null;
    weightClassification?: WeightClassification;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

