/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Bomb } from './bomb';
import { Source } from './source';


export interface BombFormulae { 
    id?: number;
    bombID?: number;
    craftDC?: number;
    time?: string | null;
    investment?: number;
    cost?: number;
    bomb?: Bomb;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

