/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Monster } from './monster';


export interface CampaignMonster { 
    id?: number;
    name?: string | null;
    monsterID?: number;
    monster?: Monster;
    _int?: number;
    ref?: number;
    dex?: number;
    body?: number;
    spd?: number;
    emp?: number;
    cra?: number;
    will?: number;
    luck?: number;
    stun?: number;
    run?: number;
    leap?: number;
    sta?: number;
    enc?: number;
    rec?: number;
    hp?: number;
    vigor?: number;
    isDead?: boolean;
    currentLocation?: string | null;
    description?: string | null;
    deleted?: boolean;
}

