/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Campaign } from './campaign';
import { CommonCover } from './commonCover';


export interface CampaignCover { 
    id?: number;
    campaignID?: number;
    commonCoverID?: number;
    campaign?: Campaign;
    commonCover?: CommonCover;
    stoppingPower?: number;
    location?: string | null;
    deleted?: boolean;
}

