/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Profession } from './profession';
import { Race } from './race';


export interface CharacterSheet { 
    characterSheetID?: number;
    name: string;
    age?: number | null;
    gender?: string | null;
    improvementPoints?: number;
    raceID?: number;
    professionID?: number;
    race?: Race;
    profession?: Profession;
    deleted?: boolean;
}

