/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CharacterSheet } from './characterSheet';
import { Weapon } from './weapon';


export interface CharacterWeapon { 
    id?: number;
    characterSheetID?: number;
    weaponID?: number;
    reliability?: number;
    weight?: number;
    isEquipped?: boolean;
    hasAmmunition?: boolean;
    weaponEnhancementsID?: number | null;
    characterSheet?: CharacterSheet;
    weapon?: Weapon;
    deleted?: boolean;
}

