/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArmorEnhancement } from './armorEnhancement';
import { CharacterSheet } from './characterSheet';
import { CharacterArmor } from './characterArmor';


export interface CharacterArmorEnhancement { 
    id?: number;
    characterSheetID?: number;
    armorEnhancementID?: number;
    isEquipped?: boolean;
    characterArmorID?: number | null;
    characterArmor?: CharacterArmor;
    characterSheet?: CharacterSheet;
    armorEnhancement?: ArmorEnhancement;
    deleted?: boolean;
}

