/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CharacterSheet } from './characterSheet';
import { Glyph } from './glyph';
import { CharacterArmor } from './characterArmor';


export interface CharacterGlyph { 
    id?: number;
    characterSheetID?: number;
    glyphID?: number;
    characterArmorID?: number | null;
    isEquipped?: boolean;
    characterSheet?: CharacterSheet;
    glyph?: Glyph;
    characterArmor?: CharacterArmor;
    deleted?: boolean;
}

