/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Armor } from './armor';
import { CharacterSheet } from './characterSheet';


export interface CharacterArmor { 
    id?: number;
    characterSheetID?: number;
    armorID?: number;
    stoppingPower?: number;
    enhancementSlotsOpen?: number;
    weight?: number;
    isEquipped?: boolean;
    characterSheet?: CharacterSheet;
    armor?: Armor;
    deleted?: boolean;
}

