/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ammunition } from './ammunition';
import { CharacterSheet } from './characterSheet';


export interface CharacterAmmunition { 
    characterSheetID?: number;
    ammunitionID?: number;
    reliability?: number;
    amount?: number;
    ammunitionEnhancementsID?: number | null;
    isEquipped?: boolean;
    characterSheet?: CharacterSheet;
    ammunition?: Ammunition;
    deleted?: boolean;
}

