/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CharacterMountVehicle } from './characterMountVehicle';
import { MountOutfit } from './mountOutfit';


export interface CharacterMountOutfit { 
    id?: number;
    characterMount_VehicleID?: number;
    mountOutfitID?: number;
    characterMount_Vehicle?: CharacterMountVehicle;
    mountOutfit?: MountOutfit;
    deleted?: boolean;
}

