/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CraftingComponentType } from './craftingComponentType';
import { Source } from './source';


export interface CraftingComponent { 
    id?: number;
    name?: string | null;
    rarity?: string | null;
    location?: string | null;
    quantity?: string | null;
    forageDC?: string | null;
    weight?: number;
    cost?: number;
    craftingComponentType?: CraftingComponentType;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

