/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SkillLevel } from './skillLevel';
import { CraftingDiagramCategory } from './craftingDiagramCategory';
import { Source } from './source';


export interface CraftingDiagram { 
    id?: number;
    name?: string | null;
    craftingDC?: number;
    time?: string | null;
    investment?: number;
    cost?: number;
    skillLevel?: SkillLevel;
    craftingDiagramCategory?: CraftingDiagramCategory;
    objectReferenceID?: number;
    amount?: number;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

