/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CraftingComponent } from './craftingComponent';
import { CraftingDiagram } from './craftingDiagram';
import { Source } from './source';


export interface CraftingDiagramComponent { 
    craftingDiagramID?: number;
    craftingComponentID?: number;
    amount?: number;
    craftingDiagram?: CraftingDiagram;
    craftingComponent?: CraftingComponent;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

