/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonsterAnatomyType } from './monsterAnatomyType';
import { CriticalWoundType } from './criticalWoundType';
import { Source } from './source';


export interface CriticalLevel { 
    id?: number;
    beatDefenseByValue?: number;
    criticalWoundType?: CriticalWoundType;
    bonusDamage?: number;
    monsterAnatomyType?: MonsterAnatomyType;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

