/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CriticalWoundType } from './criticalWoundType';
import { Source } from './source';


export interface CriticalTable { 
    id?: number;
    roll?: string | null;
    rollType?: string | null;
    effectTitle?: string | null;
    effectDescription?: string | null;
    stabilized?: string | null;
    treated?: string | null;
    criticalWoundType?: CriticalWoundType;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

