/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefiningSkill } from './definingSkill';
import { DefiningSkillTableType } from './definingSkillTableType';
import { Source } from './source';


export interface DefiningSkillTable { 
    id?: number;
    definingSkillID?: number;
    firstColumn?: string | null;
    firstColumnValue?: string | null;
    secondColumn?: string | null;
    secondColumnValue?: string | null;
    definingSkillFilter?: string | null;
    definingSkillTableType?: DefiningSkillTableType;
    definingSkill?: DefiningSkill;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

