/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DerivedStatisticCategory = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const DerivedStatisticCategory = {
    NUMBER_1: 1 as DerivedStatisticCategory,
    NUMBER_2: 2 as DerivedStatisticCategory,
    NUMBER_3: 3 as DerivedStatisticCategory,
    NUMBER_4: 4 as DerivedStatisticCategory,
    NUMBER_5: 5 as DerivedStatisticCategory,
    NUMBER_6: 6 as DerivedStatisticCategory,
    NUMBER_7: 7 as DerivedStatisticCategory,
    NUMBER_8: 8 as DerivedStatisticCategory
};

