/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Formulae } from './formulae';
import { AlchemyCategory } from './alchemyCategory';
import { Source } from './source';


export interface FormulaeComponent { 
    id?: number;
    formulaeID?: number;
    alchemyCategory?: AlchemyCategory;
    amount?: number;
    formulae?: Formulae;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

