/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GeneralGearClassification = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const GeneralGearClassification = {
    NUMBER_1: 1 as GeneralGearClassification,
    NUMBER_2: 2 as GeneralGearClassification,
    NUMBER_3: 3 as GeneralGearClassification,
    NUMBER_4: 4 as GeneralGearClassification,
    NUMBER_5: 5 as GeneralGearClassification,
    NUMBER_6: 6 as GeneralGearClassification,
    NUMBER_7: 7 as GeneralGearClassification
};

