/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Skill } from './skill';
import { Monster } from './monster';
import { Source } from './source';


export interface MonsterSkill { 
    id?: number;
    monsterID?: number;
    skillID?: number;
    value?: number;
    monster?: Monster;
    skill?: Skill;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

