/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MonsterType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13;

export const MonsterType = {
    NUMBER_1: 1 as MonsterType,
    NUMBER_2: 2 as MonsterType,
    NUMBER_3: 3 as MonsterType,
    NUMBER_4: 4 as MonsterType,
    NUMBER_5: 5 as MonsterType,
    NUMBER_6: 6 as MonsterType,
    NUMBER_7: 7 as MonsterType,
    NUMBER_8: 8 as MonsterType,
    NUMBER_9: 9 as MonsterType,
    NUMBER_10: 10 as MonsterType,
    NUMBER_11: 11 as MonsterType,
    NUMBER_12: 12 as MonsterType,
    NUMBER_13: 13 as MonsterType
};

