/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonsterInformation } from './monsterInformation';
import { MonsterWeapon } from './monsterWeapon';
import { MonsterDerivedStatistic } from './monsterDerivedStatistic';
import { MonsterLoot } from './monsterLoot';
import { Monster } from './monster';
import { MonsterSkill } from './monsterSkill';
import { MonsterStatistic } from './monsterStatistic';
import { MonsterVulnerability } from './monsterVulnerability';
import { MonsterAbility } from './monsterAbility';


export interface MonsterViewModel { 
    monster?: Monster;
    monsterAbilities?: Array<MonsterAbility> | null;
    monsterDerivedStatistics?: Array<MonsterDerivedStatistic> | null;
    monsterInformations?: Array<MonsterInformation> | null;
    monsterLoots?: Array<MonsterLoot> | null;
    monsterSkills?: Array<MonsterSkill> | null;
    monsterStatistics?: Array<MonsterStatistic> | null;
    monsterVulnerabilities?: Array<MonsterVulnerability> | null;
    monsterWeapons?: Array<MonsterWeapon> | null;
}

