/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Source } from './source';

export interface Monster {
  id?: number;
  name?: string | null;
  threat?: string | null;
  bounty?: number;
  armorValue?: number;
  height?: string | null;
  weight?: string | null;
  environment?: string | null;
  intelligence?: string | null;
  organization?: string | null;
  monsterType?: string | null;
  deleted?: boolean;
  sourceID?: number | null;
  source?: Source;
}
