/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MutagenType } from './mutagenType';
import { Source } from './source';


export interface Mutagen { 
    id?: number;
    mutagenSource?: string | null;
    effect?: string | null;
    alchemyDC?: number;
    minorMutation?: string | null;
    mutagenType?: MutagenType;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

