/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MutagenType = 1 | 2 | 3;

export const MutagenType = {
    NUMBER_1: 1 as MutagenType,
    NUMBER_2: 2 as MutagenType,
    NUMBER_3: 3 as MutagenType
};

