/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Profession } from './profession';
import { Skill } from './skill';
import { Source } from './source';


export interface ProfessionSkillPackage { 
    id?: number;
    professionID?: number;
    skillName?: string | null;
    skillID?: number | null;
    profession?: Profession;
    skill?: Skill;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

