/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProfessionCategory = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export const ProfessionCategory = {
    NUMBER_1: 1 as ProfessionCategory,
    NUMBER_2: 2 as ProfessionCategory,
    NUMBER_3: 3 as ProfessionCategory,
    NUMBER_4: 4 as ProfessionCategory,
    NUMBER_5: 5 as ProfessionCategory,
    NUMBER_6: 6 as ProfessionCategory,
    NUMBER_7: 7 as ProfessionCategory,
    NUMBER_8: 8 as ProfessionCategory,
    NUMBER_9: 9 as ProfessionCategory,
    NUMBER_10: 10 as ProfessionCategory
};

