/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RaceType = 1 | 2 | 3 | 4 | 5;

export const RaceType = {
    NUMBER_1: 1 as RaceType,
    NUMBER_2: 2 as RaceType,
    NUMBER_3: 3 as RaceType,
    NUMBER_4: 4 as RaceType,
    NUMBER_5: 5 as RaceType
};

