/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ritual } from './ritual';
import { Source } from './source';


export interface RitualComponent { 
    id?: number;
    ritualID?: number;
    componentName?: string | null;
    amount?: number | null;
    ritual?: Ritual;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

