/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SkillCategory = 1 | 1 | 1 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50;

export const SkillCategory = {
    NUMBER_1: 1 as SkillCategory,
    NUMBER_2: 2 as SkillCategory,
    NUMBER_3: 3 as SkillCategory,
    NUMBER_4: 4 as SkillCategory,
    NUMBER_5: 5 as SkillCategory,
    NUMBER_6: 6 as SkillCategory,
    NUMBER_7: 7 as SkillCategory,
    NUMBER_8: 8 as SkillCategory,
    NUMBER_9: 9 as SkillCategory,
    NUMBER_10: 10 as SkillCategory,
    NUMBER_11: 11 as SkillCategory,
    NUMBER_12: 12 as SkillCategory,
    NUMBER_13: 13 as SkillCategory,
    NUMBER_14: 14 as SkillCategory,
    NUMBER_15: 15 as SkillCategory,
    NUMBER_16: 16 as SkillCategory,
    NUMBER_20: 20 as SkillCategory,
    NUMBER_21: 21 as SkillCategory,
    NUMBER_22: 22 as SkillCategory,
    NUMBER_23: 23 as SkillCategory,
    NUMBER_24: 24 as SkillCategory,
    NUMBER_25: 25 as SkillCategory,
    NUMBER_26: 26 as SkillCategory,
    NUMBER_27: 27 as SkillCategory,
    NUMBER_28: 28 as SkillCategory,
    NUMBER_29: 29 as SkillCategory,
    NUMBER_30: 30 as SkillCategory,
    NUMBER_31: 31 as SkillCategory,
    NUMBER_32: 32 as SkillCategory,
    NUMBER_33: 33 as SkillCategory,
    NUMBER_34: 34 as SkillCategory,
    NUMBER_35: 35 as SkillCategory,
    NUMBER_36: 36 as SkillCategory,
    NUMBER_37: 37 as SkillCategory,
    NUMBER_38: 38 as SkillCategory,
    NUMBER_39: 39 as SkillCategory,
    NUMBER_40: 40 as SkillCategory,
    NUMBER_41: 41 as SkillCategory,
    NUMBER_42: 42 as SkillCategory,
    NUMBER_43: 43 as SkillCategory,
    NUMBER_44: 44 as SkillCategory,
    NUMBER_45: 45 as SkillCategory,
    NUMBER_46: 46 as SkillCategory,
    NUMBER_47: 47 as SkillCategory,
    NUMBER_48: 48 as SkillCategory,
    NUMBER_49: 49 as SkillCategory,
    NUMBER_50: 50 as SkillCategory
};

