/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Statistic } from './statistic';
import { Source } from './source';
import { SkillCategory } from './skillCategory';


export interface Skill { 
    id?: number;
    name?: string | null;
    description?: string | null;
    pointsPerLevel?: number;
    skillCategory?: SkillCategory;
    statisticID?: number;
    statistic?: Statistic;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

