/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SpellTypeClassification = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const SpellTypeClassification = {
    NUMBER_1: 1 as SpellTypeClassification,
    NUMBER_2: 2 as SpellTypeClassification,
    NUMBER_3: 3 as SpellTypeClassification,
    NUMBER_4: 4 as SpellTypeClassification,
    NUMBER_5: 5 as SpellTypeClassification,
    NUMBER_6: 6 as SpellTypeClassification,
    NUMBER_7: 7 as SpellTypeClassification,
    NUMBER_8: 8 as SpellTypeClassification
};

