/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Trap } from './trap';
import { TrapDiagram } from './trapDiagram';
import { TrapDiagramComponent } from './trapDiagramComponent';


export interface TrapViewModel { 
    trap?: Trap;
    trapDiagram?: TrapDiagram;
    trapDiagramComponents?: Array<TrapDiagramComponent> | null;
}

