/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeaponEffect } from './weaponEffect';
import { Weapon } from './weapon';
import { CraftingDiagram, CraftingDiagramComponent } from './models';

export interface WeaponViewModel {
  weapon?: Weapon;
  weaponEffects?: Array<WeaponEffect> | null;
  craftingDiagram?: CraftingDiagram;
  craftingDiagramComponents?: Array<CraftingDiagramComponent> | null;
}
