/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Availability } from './availability';
import { Concealment } from './concealment';
import { WeaponClassification } from './weaponClassification';
import { Source } from './source';

export interface Weapon {
  id?: number;
  name?: string | null;
  attackType?: string | null;
  weaponAccuracy?: number;
  availability?: Availability;
  damage?: string | null;
  defaultReliability?: number;
  handsRequired?: number;
  range?: string | null;
  concealment?: string;
  enhancements?: number;
  weight?: number;
  cost?: number;
  description?: string | null;
  weaponClassification?: string;
  deleted?: boolean;
  sourceID?: number | null;
  source?: Source;
}
