/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WeaponClassification = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export const WeaponClassification = {
    NUMBER_1: 1 as WeaponClassification,
    NUMBER_2: 2 as WeaponClassification,
    NUMBER_3: 3 as WeaponClassification,
    NUMBER_4: 4 as WeaponClassification,
    NUMBER_5: 5 as WeaponClassification,
    NUMBER_6: 6 as WeaponClassification,
    NUMBER_7: 7 as WeaponClassification,
    NUMBER_8: 8 as WeaponClassification,
    NUMBER_9: 9 as WeaponClassification
};

