/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpellTypeClassification } from './spellTypeClassification';
import { WitcherSignClassification } from './witcherSignClassification';
import { Source } from './source';


export interface WitcherSign { 
    id?: number;
    name?: string | null;
    spellTypeClassification?: SpellTypeClassification;
    staminaCost?: string | null;
    effect?: string | null;
    range?: string | null;
    duration?: string | null;
    defense?: string | null;
    witcherSignClassification?: WitcherSignClassification;
    deleted?: boolean;
    sourceID?: number | null;
    source?: Source;
}

