/**
 * Witcher API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WitcherSignClassification = 1 | 2;

export const WitcherSignClassification = {
    NUMBER_1: 1 as WitcherSignClassification,
    NUMBER_2: 2 as WitcherSignClassification
};

